source $XDG_CONFIG_HOME/zsh/antigen.zsh

antigen bundle mafredri/zsh-async
antigen bundle intelfx/pure
antigen bundle wting/autojump
antigen bundle j-arnaiz/common-aliases

antigen apply

source $HOME/.antigen/bundles/wting/autojump/bin/autojump.zsh

alias ls="ls --color"


export GOPATH=$HOME/.go
export ANDROID_HOME=/opt/android-sdk
export ANDROID_SDK_ROOT=$ANDROID_HOME

export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
export PATH=$PATH:$ANDROID_SDK_ROOT/tools
export PATH=$PATH:$ANDROID_NDK
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$HOME/.gem/ruby/2.5.0/bin
export PATH=$PATH:$HOME/.gem/ruby/2.4.0/bin
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:`yarn global bin --offline`
export EDITOR=nvim

source /usr/share/nvm/init-nvm.sh

if [[ $TERM == xterm-termite ]]; then
  . /etc/profile.d/vte.sh
  __vte_osc7
fi

source $XDG_CONFIG_HOME/zsh/keybinds

# Les features!
# extended globbing, awesome!
# setopt extendedGlob

# zmv -  a command for renaming files by means of shell patterns.
# autoload -U zmv
#
# # zargs, as an alternative to find -exec and xargs.
# autoload -U zargs
#
# Control-x-e to open current line in $EDITOR, awesome when writting functions or editing multiline commands.
autoload -U edit-command-line
zle -N edit-command-line

# Ignore duplicate in history.
setopt hist_ignore_dups

# Prevent record in history entry if preceding them with at least one space
setopt hist_ignore_space

# Nobody needs flow control anymore.
# setopt noflowcontrol

HISTFILE=$XDG_CONFIG_HOME/zsh/zsh_history
HISTSIZE=10000
SAVEHIST=10000

setopt appendhistory autocd beep extendedglob notify
bindkey -v # You can't stop here, you're in Vim country!...

bindkey '^R' history-incremental-search-backward
bindkey '^x^e' edit-command-line

# source /usr/share/autojump/autojump.zsh

source <(gopass completion zsh)
complete -F _gopass_bash_autocomplete pass

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
