root:
  askformore: true
  autoclip: false
  autoimport: true
  autosync: false
  check_recipient_hash: false
  cliptimeout: 45
  concurrency: 1
  editrecipients: false
  nocolor: false
  noconfirm: false
  nopager: false
  notifications: false
  path: gpgcli-gitcli-fs+file:///home/ghjkl/.password-store
  recipient_hash: {}
  safecontent: false
  usesymbols: false
mounts: {}
